default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hiromatsubook_development
test:
  <<: *default
  database: hiromatsubook_test
production:
  <<: *default
  database: hiromatsubook_production
  username: hiromatsubook
  password: <%= ENV['HIROMATSUBOOK_DATABASE_PASSWORD'] %>
